---

- name: Install reuired system packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - python-psycopg2
    - python3-distutils
    - uwsgi-plugin-python3
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3-setuptools
  tags:
    - python

- name: Install PIP packages
  become: true
  pip:
    name: virtualenv
  tags:
    - python